/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myhashmap;

import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class HashMapTest {
    @Test
    void put() {
        Map<String, Integer> map = new HashMap<>();

        assertThat(map.put("Jin", 17)).isEqualTo(17);
    }

    @Test
    void putAndGet() {
        HashMap<String, Integer> map = new HashMap<>();

        map.put("Jin", 17);

        assertThat(map.get("Jin")).isEqualTo(17);
    }
}
