/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package money;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MoneyTest {
    @Test void times() {
        // 할 일
        // - 5 dollar * 2 = 10 dollar
        // => TDD by example
        // 유용하면서도 본질적인 시스템 사용의 예시를 찾아서 제시함.
        Dollar five = new Dollar(5);
        five.times(2);
        assertEquals(10, five.amount);
    }
}
