/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package krane;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

class BoardTest {
    @Test
    void pick() {
        int[][] arrangement = {
                {0, 0, 0, 0, 0},
                {0, 0, 0, 0, 0},
                {0, 0, 0, 0, 0},
                {2, 0, 0, 0, 0},
                {1, 3, 0, 0, 0}
        };
        Board board = new Board(arrangement);

        assertEquals(arrangement[3][0], board.pick(1));
        assertEquals(arrangement[4][0], board.pick(1));
        assertEquals(arrangement[4][1], board.pick(2));
    }

    @Test
    void pickReturnsNull() {
        int[][] arrangement = {
                {0, 0, 0, 0, 0},
                {0, 0, 0, 0, 0},
                {0, 0, 0, 0, 0},
                {0, 0, 0, 0, 0},
                {0, 0, 0, 0, 0}
        };
        Board board = new Board(arrangement);

        assertNull(board.pick(1));
    }
}
