/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package defense.game;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
//### 로직 구체화
//1. 남은 병사가 적군보다 많다면, 싸운다.
//2. 남은 병사가 적군보다 적으면,
//    - 부활권이 없다면 패배
//    - 부활한다 => 1, 2 반복

// TODO.
// 1. 클라이언트 인터페이스 설계 -> 샘플 테스트를 이용.
// 2. Army에 대한 테스트 -> 행위 중심, 핵심 동작은 defeat.
    @Test void sample1() {
        Solution solution = new Solution();
        assertEquals(5, solution.solution(7, 3, new int[]{4, 2, 4, 5, 3, 3, 1}));
    }

    @Test void sample2() {
        Solution solution = new Solution();
        assertEquals(4, solution.solution(2, 4, new int[]{3, 3, 3, 3}));
    }
}
