/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trie;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    @Test
    void addAndSearch() {
        WordDictionary wordDictionary = new WordDictionary();

        wordDictionary.addWord("bad");

        assertTrue(wordDictionary.search("bad"));
    }
}
