/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clean.code.args.example;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class ArgsTest {
    @Test
    void singleBooleanArgumentSet() {
        Args args = new Args("x", new String[]{"-x"});
        assertThat(args.getBoolean('x')).isTrue();

        assertThat(args.cardinality()).isEqualTo(1);
    }

    @Test
    void singleBooleanArgumentUnset() {
        Args args = new Args("x", new String[]{""});
        assertThat(args.getBoolean('x')).isFalse();
    }

    @Test
    void multipleBooleanArguments() {
        Args args = new Args("x,y,z", new String[]{"-xy"});

        assertThat(args.getBoolean('x')).isTrue();
        assertThat(args.getBoolean('y')).isTrue();
        assertThat(args.getBoolean('z')).isFalse();

        assertThat(args.cardinality()).isEqualTo(3);
    }

    @Test
    void validArguments() {
        Args args = new Args("x", new String[]{"-x"});

        assertThat(args.isValid()).isTrue();

        assertThat(args.errorMessage()).isEqualTo("");
    }

    @Test
    void invalidArguments() {
        Args args = new Args("", new String[]{"-xy"});

        assertThat(args.isValid()).isFalse();

        assertThat(args.errorMessage()).isEqualTo("Argument(s) -xy unexpected.");
    }
}
