/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ctci.java;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AnagramTest {
    boolean isAnagram(String string1, String string2) {
        if (string1.length() != string2.length()) {
            return false;
        }

        int[] counts = new int[128];

        for (char c : string1.toCharArray()) {
            counts[c] += 1;
        }

        for (char c : string2.toCharArray()) {
            if (counts[c] == 0) {
                return false;
            }
            counts[c] -= 1;
        }

        return true;
    }

    @Test void testIsAnagram() {
        assertTrue(isAnagram("abc", "cab"));
        assertFalse(isAnagram("abcd", "cabf"));
    }

    @Test void testIsAnagramWithDifferentLength() {
        assertFalse(isAnagram("abc", "cabd"));
    }
}
