/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gringrape.mineSweeper;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("--- 지뢰찾기 게임 ---");

        Board board = new Board(5);

        while (board.isSearching()) {
            display(board.toArray());

            // Input
            System.out.println("지뢰가 있는 행의 번호를 입력하세요. (0~4)");
            int row = scanner.nextInt();
            System.out.println("지뢰가 있는 열의 번호를 입력하세요. (0~4)");
            int column = scanner.nextInt();

            // Process
            board.select(row, column);
        }

        // Output
        if (board.isDestroyed()) {
            System.out.println("지뢰 폭파!");
            return;
        }

        System.out.println("게임 클리어!");
    }

    private static void display(String[][] array) {
        for (String[] row : array) {
            for (String element : row) {
                System.out.print(element + " ");
            }
            System.out.println();
        }
    }
}
