/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package calculator

import org.junit.jupiter.api.assertThrows
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull

class CalculatorTest {
    @Test
    fun testAdd() {
        assertEquals(3, add("1,2"))
        assertEquals(1, add("1"))
        assertEquals(0, add(""))
    }

    @Test
    fun testAddNewLines() {
        assertEquals(3, add("1\\n2"))
        assertEquals(6, add("1\\n2,3"))
    }

    @Test
    fun testNegativeThrowsError() {
        val exception = assertFailsWith<Error>(
            block = {
                add("1,-2,-3")
            }
        )

        assertEquals(
            "negatives not allowed, -2,-3",
            exception.message,
        )
    }

    private fun add(numbers: String): Int {
        if (numbers.isEmpty()) {
            return 0
        }

        val positives = numbers
            .split(",", "\\n")
            .map { it.toInt() }

        if (positives.any { it < 0 }) {
            val negatives = positives
                .filter { it < 0 }
                .joinToString(",") { it.toString() }

            throw Error("negatives not allowed, $negatives")
        }

        return positives.sum()
    }
}
