/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ctci.java;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    boolean isPalindromeAnagram(String word) {
        BitVector bits = new BitVector();

        for (char letter : word.toCharArray()) {
            int index = letter - 'a';
            bits.toggle(index);
        }

        return bits.sumOfDigits() <= 1;
    }

    @Test
    void testIsPalindromeAnagramEvenLength() {
        assertTrue(isPalindromeAnagram("abba"));
        assertTrue(isPalindromeAnagram("aabb"));
    }

    @Test
    void testIsPalindromeAnagramOddLength() {
        assertTrue(isPalindromeAnagram("aaabb"));
    }
}
